name: Project Absence CLI CD (Publish)

on:
  push:
    tags:
      - "cli_*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Publish
        run: cd cli && cargo publish --verbose --all-features --token ${{ secrets.CARGO_TOKEN }}